@isTest
private class HelloWorldTestClass {
    static testMethod void validateHelloWorld() {
       // Account a = new Account(Name='Usr1');
       // System.debug('Account before inserting new account: ' + a.Name);
       // insert a;
       // Account b = [SELECT Name FROM Account WHERE Id =:a.Id];
       // System.debug('Account after trigger fired: ' + b.Name);
      //System.assertEquals('Usr11', b.Name);
    }
}